"""Generate the FiveM resource(s) around a finished ``.ycd``.

Two resources can be produced:

``<name>/``            the animation itself, ready to drop into
                       ``resources/[animations]/``
``<name>_test/``       the same animation plus a ``client.lua`` exposing
                       ``/testanim``, for checking the result in game

A clip dictionary streamed by a resource is addressed by the **`.ycd` filename
without its extension**, so ``my_dance.ycd`` becomes the animation dictionary
``"my_dance"``. That is why the file name, the dictionary name and the clip name
are all derived from one sanitised string - see ``ycd_xml.sanitize_name``.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

FXMANIFEST = """fx_version 'cerulean'
game 'gta5'

name '{name}'
author '{author}'
description '{description}'
version '1.0.0'

-- A clip dictionary is addressed in game by its file name without the
-- extension, so this streams as the animation dictionary '{name}'.
files {{
    'stream/{name}.ycd'
}}
"""

FXMANIFEST_TEST = """fx_version 'cerulean'
game 'gta5'

name '{name}_test'
author '{author}'
description 'Test resource for the {name} animation - provides /testanim'
version '1.0.0'

client_script 'client.lua'

files {{
    'stream/{name}.ycd'
}}
"""

CLIENT_LUA = """--[[
    Test resource for the '{name}' animation.

    Usage in the F8 console or chat:
        /testanim              -> plays '{clip}' from dictionary '{name}'
        /testanim <clip>       -> plays a specific clip from that dictionary
        /testanim <dict> <clip>-> plays any clip from any dictionary
        /stopanim              -> clears the animation

    Requesting the dictionary and waiting for it to load is mandatory. Calling
    TaskPlayAnim without it is the single most common reason a custom animation
    silently does nothing.
]]

local DEFAULT_DICT = '{name}'
local DEFAULT_CLIP = '{clip}'

local function loadDict(dict)
    if not DoesAnimDictExist(dict) then
        return false, ('animation dictionary "%s" does not exist (is the resource started and streamed?)'):format(dict)
    end

    RequestAnimDict(dict)

    -- Give up rather than spin forever if the stream never arrives.
    local timeout = GetGameTimer() + 5000
    while not HasAnimDictLoaded(dict) do
        if GetGameTimer() > timeout then
            return false, ('timed out loading "%s"'):format(dict)
        end
        Wait(0)
    end

    return true
end

RegisterCommand('testanim', function(_, args)
    local dict, clip

    if #args >= 2 then
        dict, clip = args[1], args[2]
    elseif #args == 1 then
        dict, clip = DEFAULT_DICT, args[1]
    else
        dict, clip = DEFAULT_DICT, DEFAULT_CLIP
    end

    local ok, err = loadDict(dict)
    if not ok then
        print(('[{name}_test] %s'):format(err))
        return
    end

    TaskPlayAnim(
        PlayerPedId(),
        dict, clip,
        8.0,      -- blend in
        -8.0,     -- blend out
        -1,       -- duration: -1 plays the whole clip
        1,        -- flag 1 = loop
        0.0,      -- start phase
        false, false, false
    )

    print(('[{name}_test] playing %s / %s'):format(dict, clip))
end, false)

RegisterCommand('stopanim', function()
    ClearPedTasks(PlayerPedId())
    print('[{name}_test] stopped')
end, false)
"""

RESOURCE_README = """# {name}

A FiveM animation resource, generated by the FBX -> FiveM Animation Converter.

## Install

Copy this folder into your server's resources, for example:

```
resources/[animations]/{name}/
```

and add it to your `server.cfg`:

```
ensure {name}
```

## Play it

The animation dictionary is `{name}` and the clip is `{clip}`.

```lua
local dict, clip = '{name}', '{clip}'

RequestAnimDict(dict)
while not HasAnimDictLoaded(dict) do Wait(0) end

TaskPlayAnim(PlayerPedId(), dict, clip, 8.0, -8.0, -1, 1, 0.0, false, false, false)
```

`RequestAnimDict` + the `HasAnimDictLoaded` wait are required. Without them
`TaskPlayAnim` does nothing.

The `flag` argument (the `1` above) controls playback:

| Flag | Meaning |
| --- | --- |
| `0` | play once, then return to normal |
| `1` | loop |
| `2` | hold the last frame |
| `16` | additive-style upper-body only |

## Source

| | |
| --- | --- |
| Source file | `{source_file}` |
| Frames | {frame_count} |
| Frame rate | {fps} fps |
| Duration | {duration:.3f} s |
| Target skeleton | {skeleton} |
| Animated bones | {bone_count} |
"""


@dataclass
class ResourceResult:
    root: Path
    manifest: Path
    ycd: Path | None
    ycd_xml: Path | None
    readme: Path
    test_root: Path | None = None


def _write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def generate_resource(
    output_dir: Path,
    name: str,
    clip: str,
    ycd_path: Path | None,
    ycd_xml_path: Path | None,
    *,
    frame_count: int,
    fps: float,
    duration: float,
    bone_count: int,
    skeleton: str,
    source_file: str,
    author: str = "FBX -> FiveM Animation Converter",
    description: str = "",
    with_test_resource: bool = False,
) -> ResourceResult:
    """Write ``output_dir/<name>/`` and optionally ``output_dir/<name>_test/``."""
    root = Path(output_dir) / name
    stream = root / "stream"
    stream.mkdir(parents=True, exist_ok=True)

    manifest = _write(
        root / "fxmanifest.lua",
        FXMANIFEST.format(
            name=name,
            author=author,
            description=description or f"'{clip}' animation for FiveM",
        ),
    )

    installed_ycd: Path | None = None
    if ycd_path is not None and Path(ycd_path).is_file():
        installed_ycd = stream / f"{name}.ycd"
        shutil.copyfile(ycd_path, installed_ycd)

    # The XML is kept alongside the resource even on success: it is the
    # reviewable, diffable form of the animation, and it is what the user needs
    # if they ever want to convert it by hand in CodeWalker.
    installed_xml: Path | None = None
    if ycd_xml_path is not None and Path(ycd_xml_path).is_file():
        installed_xml = root / f"{name}.ycd.xml"
        shutil.copyfile(ycd_xml_path, installed_xml)

    readme = _write(
        root / "README.md",
        RESOURCE_README.format(
            name=name,
            clip=clip,
            frame_count=frame_count,
            fps=fps,
            duration=duration,
            bone_count=bone_count,
            skeleton=skeleton,
            source_file=source_file,
        ),
    )

    test_root: Path | None = None
    if with_test_resource:
        test_root = Path(output_dir) / f"{name}_test"
        (test_root / "stream").mkdir(parents=True, exist_ok=True)
        _write(
            test_root / "fxmanifest.lua",
            FXMANIFEST_TEST.format(name=name, author=author),
        )
        _write(test_root / "client.lua", CLIENT_LUA.format(name=name, clip=clip))
        if installed_ycd is not None:
            shutil.copyfile(installed_ycd, test_root / "stream" / f"{name}.ycd")

    return ResourceResult(
        root=root,
        manifest=manifest,
        ycd=installed_ycd,
        ycd_xml=installed_xml,
        readme=readme,
        test_root=test_root,
    )
